# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_arm_controller
    - right_arm_controller
    - left_gripper_controller
    - right_gripper_controller
    # - left_side_controller
    # - right_side_controller
    # - upper_body_controller

  left_arm_controller:
    type: FollowJointTrajectory
    joints:
      - openarm_left_joint1
      - openarm_left_joint2
      - openarm_left_joint3
      - openarm_left_joint4
      - openarm_left_joint5
      - openarm_left_joint6
      - openarm_left_joint7
    action_ns: follow_joint_trajectory
  right_arm_controller:
    type: FollowJointTrajectory
    joints:
      - openarm_right_joint1
      - openarm_right_joint2
      - openarm_right_joint3
      - openarm_right_joint4
      - openarm_right_joint5
      - openarm_right_joint6
      - openarm_right_joint7
    action_ns: follow_joint_trajectory
  left_gripper_controller:
    type: FollowJointTrajectory
    joints:
      - openarm_left_finger_joint1
    action_ns: left_pris_1
    default: true
  right_gripper_controller:
    type: FollowJointTrajectory
    joints:
      - openarm_right_finger_joint1
    action_ns: right_pris_1
    default: true

  # left_side_controller:
  #   type: FollowJointTrajectory
  #   joints:
  #     - openarm_left_joint1
  #     - openarm_left_joint2
  #     - openarm_left_joint3
  #     - openarm_left_joint4
  #     - openarm_left_joint5
  #     - openarm_left_joint6
  #     - openarm_left_joint7
  #     - openarm_left_finger_joint1
  # right_side_controller:
  #   type: FollowJointTrajectory
  #   joints:
  #     - openarm_right_joint1
  #     - openarm_right_joint2
  #     - openarm_right_joint3
  #     - openarm_right_joint4
  #     - openarm_right_joint5
  #     - openarm_right_joint6
  #     - openarm_right_joint7
  #     - openarm_right_finger_joint1
  # upper_body_controller:
  #   type: FollowJointTrajectory
  #   joints:
  #     - openarm_left_joint1
  #     - openarm_left_joint2
  #     - openarm_left_joint3
  #     - openarm_left_joint4
  #     - openarm_left_joint5
  #     - openarm_left_joint6
  #     - openarm_left_joint7
  #     - openarm_left_finger_joint1
  #     - openarm_right_joint1
  #     - openarm_right_joint2
  #     - openarm_right_joint3
  #     - openarm_right_joint4
  #     - openarm_right_joint5
  #     - openarm_right_joint6
  #     - openarm_right_joint7
  #     - openarm_right_finger_joint1
